apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - main

jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build 
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true


  StaticAnalysis:
    needs: Build
    steps:
      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
        name: Scan
        kind: scan
        with:
          server-url: https://sonarqube.cb-demos.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          language: Java

      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: Scan with Java
        kind: scan
        with:
          language: JAVA

      - uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        name: Scan with Find Security Bugs
        kind: scan
        with:
          language: LANGUAGE_JAVA

      - uses: sbatchelder-cba/sonarqube-cba@v0.0.3
        name: Scan GP
        with:
          project-key: apigateway
          token: ${{ secrets.token }}


  DockerImageBuildAndPush:
    needs: StaticAnalysis
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true
      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ secrets.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}

      - name: Push image to OCI registry
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.STAGING_DOCKER_REGISTRY }}/${{ secrets.STAGING_DOCKER_USERNAME }}/api-gateway:3.2.4
          build-args: docker images

  DeployInGKE:
    needs: DockerImageBuildAndPush
    steps: 
      - name: Checkout
        uses: cloudbees-io/checkout@v1
         
      - name: Install kubectl
        uses: docker://google/cloud-sdk:latest
        run: |
          export KUBECONFIG=/cloudbees/workspace/kubeconfig.yaml
          kubectl config view
          kubectl cluster-info
          kubectl apply -f /cloudbees/workspace/deployment-service.yaml
          kubectl get pods -n ashok
          kubectl get svc -n ashok

      - name: Get External IP and Port
        uses: docker://google/cloud-sdk:latest
        run: |
          export KUBECONFIG=/cloudbees/workspace/kubeconfig.yaml
          EXTERNAL_IP=$(kubectl get svc apigateway-service -n ashok -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
          PORT=$(kubectl get svc apigateway-service -n ashok -o=jsonpath='{.spec.ports[0].port}')
          echo "External IP: $EXTERNAL_IP"
          echo "Port: $PORT"